stages:
  - build
  - test
  - lint
  - style
  - publish

before_script:
  - make setup

build:
  stage: build
  tags:
    - server
  script:
    - make build

test:
  stage: test
  tags:
    - server
  script:
    - make test

test_examples:
  stage: test
  tags:
    - server
  script:
    - make test_examples

lint:
  stage: lint
  tags:
    - server
  script:
    - make lint

style:
  stage: style
  tags:
    - server
  script:
    - make check_style

publish:
  stage: publish
  tags:
    - server
  script:
    - make publish
  when: manual
  only:
    - master
