stages:
  - build
  - test
  - deploy

cache:
  paths:
    - target/
    - ~/.cargo/

build:
  stage: build
  tags:
    - server
  script:
    - cargo build

unit_tests:
  stage: test
  tags:
    - server
  script:
    - cargo test unit_tests

integration_tests:
  stage: test
  tags:
    - server
  script:
    - cargo test integration_tests

deploy:
  stage: deploy
  tags:
    - server
  script:
    - cargo login <($CRATES_TOKEN)
    - cargo package
    - cargo publish
  when: manual
  only:
    - master