[package]
name = "tmdb-sans-io"
version = "0.1.0"
authors = ["Daniel Lambert <danjl1100@gmail.com>"]
description = "The Movie Database (TMDb) API for Rust"
readme = "README.md"
license = "MIT"

[dependencies]
serde = "1.0.123"
serde_derive = "1.0.123"
reqwest = "0.9.5"
